name: Release Add-On Pipeline

on:
  workflow_dispatch:
  push:
        

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{matrix.os-type}}

    strategy:
      matrix:
        os-type: [ windows-2019, macos-latest ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Checkout the submodule
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Download latest APIDevKit release
        env:
          FILE_NAME: ${{ runner.os == 'Windows' && '*WIN*.zip' || '*MAC*.zip' }}
        uses: robinraju/release-downloader@v1.8
        with:
          repository: GRAPHISOFT/archicad-api-devkit-internal
          latest: true
          fileName: ${{ env.FILE_NAME }}
          extract: false
          out-file-path: apidevkit-release
          token: ${{ secrets.PAT_CLASSIC }}

      - name: unzip
        run: unzip apidevkit-release/${{ runner.os == 'Windows' && '*WIN*.zip' || '*MAC*.zip' }} -d "${{ github.workspace }}/apidevkit-release"     

      - name: python version
        run: python --version
      - name: run python
        run: python test.py --acVersion "27" --language "INT" --devKitPath "${{ github.workspace }}\apidevkit-release" --package --release

      - name: list dirs
        run: ls .

      - name: list dirs
        run: ls ./Build

      - name: list dirs
        run: ls ./Build/Package

      - name: where am i
        run: pwd
          
      # - name: Increase tag version
      #   uses: anothrNick/github-tag-action@1.64.0 
      #   id: tagSet
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
      #     WITH_V: false
      #     INITIAL_VERSION: "0.0.0"
      #     DEFAULT_BUMP: patch
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 0.0.0
          files: "${{ github.workspace }}/Build/Package/ExampleAddOn_WIN.zip"
            
            
      
