name: Release Add-On Pipeline

on:
  workflow_dispatch:
  # push:
  #   branches: [ "separated-addon-pipelines" ]
        

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ${{matrix.os-type}}
    outputs:
      releaseVersion: ${{ steps.setVersion.outputs.version }}

    strategy:
      matrix:
        os-type: [ windows-2019 ]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Checkout the submodule
        uses: actions/checkout@v3
        with:
          submodules: recursive
      
      - name: Download latest APIDevKit release
        uses: robinraju/release-downloader@v1.8
        with:
          repository: GRAPHISOFT/archicad-api-devkit-internal
          latest: true
          extract: false
          out-file-path: apidevkit-release
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: unzip
        run: unzip apidevkit-release/${{ runner.os == 'Windows' && '*WIN*.zip' || '*MAC*.zip' }} -d "${{ github.workspace }}/apidevkit-release"     

      - name: run python
        run: python test.py --acVersion "27" --language "INT" --devKitPath "${{ github.workspace }}/apidevkit-release" --package

      - name: list dirs
        run: |
          ls .
          ls ./Build
          ls ./Build/Package


  #     - name: Store artifact
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: ${{ github.event.repository.name }}-${{ matrix.os-type }}-Release-localized
  #         path: "${{ github.workspace }}/Localized-Builds/*"
  
  # release:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Download artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         path: "${{ github.workspace }}/artifacts"

  #     - name: Zip artifact contents
  #       run: |
  #         base_directory="${{ github.workspace }}/artifacts"
  #         cd $base_directory
  #         ls .

  #         for subdirectory in "$base_directory"/*; do
  #           if [ -d "$subdirectory" ]; then
  #             subdirectory_basename=$(basename "$subdirectory")
  #             pushd "$subdirectory"
  #             zip -r "${subdirectory_basename}.zip" .
  #             popd
  #           fi        
  #         done
          
  #     - name: Increase tag version
  #       uses: anothrNick/github-tag-action@1.64.0 
  #       id: tagSet
  #       env:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 
  #         WITH_V: false
  #         INITIAL_VERSION: "${{ needs.build.outputs.releaseVersion }}.0"
  #         DEFAULT_BUMP: patch
          
  #     - name: Create Release
  #       uses: softprops/action-gh-release@v1
  #       with:
  #         tag_name: "${{ steps.tagSet.outputs.new_tag }}"
  #         files: "${{ github.workspace }}/artifacts/*/*.zip"
            
            
      
